apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
      - name: prerendering
        image: gcr.io/suzuito-godzilla/prerendering:latest
        ports:
        - containerPort: 10080
        readinessProbe:
          httpGet:
            path: /
            port: 10080

