
steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/suzuito-${_ENV}/server-go"
  - "--file=./Dockerfile.server"
  - .
- name: "k8s.gcr.io/kustomize/kustomize:v4.3.0"
  args: ['build', 'kustomize/${_APP}/${_ENV}/${_REGION}', '--output=_.yaml']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=_.yaml
  - --location=${_REGION}
  - --cluster=autopilot-asia-northeast1
- name: "gcr.io/cloud-builders/kubectl"
  env:
  - CLOUDSDK_COMPUTE_REGION=${_REGION}
  - CLOUDSDK_CONTAINER_CLUSTER=autopilot-asia-northeast1
  args:
  - rollout
  - restart
  - deployment/front-deployment
  - --namespace=${_APP}
images:
- gcr.io/suzuito-${_ENV}/server-go