version: '3'
services:
  blog1-server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    ports:
      - 8080:8080
    environment:
      - ENV=dev
      - PRERENDER_URL=https://render-tron.appspot.com
      - FRONT_URL=https://suzuito.github.io/test_pages
    command: /bin/bash -c 'air -c .air-server.toml'
    