version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    ports:
      - 8080:8080
    environment:
      - ENV=godzilla
      - PRERENDER_URL=http://prerendering:8080
      - FRONT_URL=https://suzuito-minilla-blog1-server.storage.googleapis.com
    links:
      - prerendering:prerendering
    depends_on:
      - prerendering
    command: /bin/bash -c 'air -c .air-server.toml'
  prerendering:
    image: gcr.io/suzuito-godzilla/prerendering:latest
    ports:
      - 8081:8080
