// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/reverse_proxy.go

// Package usecase is a generated GoMock package.
package usecase

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockReverseProxy is a mock of ReverseProxy interface.
type MockReverseProxy struct {
	ctrl     *gomock.Controller
	recorder *MockReverseProxyMockRecorder
}

// MockReverseProxyMockRecorder is the mock recorder for MockReverseProxy.
type MockReverseProxyMockRecorder struct {
	mock *MockReverseProxy
}

// NewMockReverseProxy creates a new mock instance.
func NewMockReverseProxy(ctrl *gomock.Controller) *MockReverseProxy {
	mock := &MockReverseProxy{ctrl: ctrl}
	mock.recorder = &MockReverseProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReverseProxy) EXPECT() *MockReverseProxyMockRecorder {
	return m.recorder
}

// ServeHTTP mocks base method.
func (m *MockReverseProxy) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", rw, req)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockReverseProxyMockRecorder) ServeHTTP(rw, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockReverseProxy)(nil).ServeHTTP), rw, req)
}

// MockReverseProxyFactory is a mock of ReverseProxyFactory interface.
type MockReverseProxyFactory struct {
	ctrl     *gomock.Controller
	recorder *MockReverseProxyFactoryMockRecorder
}

// MockReverseProxyFactoryMockRecorder is the mock recorder for MockReverseProxyFactory.
type MockReverseProxyFactoryMockRecorder struct {
	mock *MockReverseProxyFactory
}

// NewMockReverseProxyFactory creates a new mock instance.
func NewMockReverseProxyFactory(ctrl *gomock.Controller) *MockReverseProxyFactory {
	mock := &MockReverseProxyFactory{ctrl: ctrl}
	mock.recorder = &MockReverseProxyFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReverseProxyFactory) EXPECT() *MockReverseProxyFactoryMockRecorder {
	return m.recorder
}

// NewReverseProxy mocks base method.
func (m *MockReverseProxyFactory) NewReverseProxy(transport http.RoundTripper) ReverseProxy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewReverseProxy", transport)
	ret0, _ := ret[0].(ReverseProxy)
	return ret0
}

// NewReverseProxy indicates an expected call of NewReverseProxy.
func (mr *MockReverseProxyFactoryMockRecorder) NewReverseProxy(transport interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewReverseProxy", reflect.TypeOf((*MockReverseProxyFactory)(nil).NewReverseProxy), transport)
}
