apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: front
        image: gcr.io/suzuito-godzilla/server-go:latest
        resources:
          requests:
            cpu: 186m
            memory: 384Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        env:
          - name: ENV
            value: prd
          - name: PRERENDER_URL
            value: http://127.0.0.1:10080
          - name: FRONT_URL
            value: https://suzuito-godzilla-blog1-server.storage.googleapis.com
      - name: prerendering
        image: gcr.io/suzuito-godzilla/prerendering:latest
        resources:
          requests:
            cpu: 186m
            memory: 384Mi
          limits:
            cpu: 1000m
            memory: 512Mi
      nodeSelector:
        cloud.google.com/gke-spot: "true"
