name: deploy-suzuito-minilla

on:
  push:
    tags:
      - "qa"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: suzuito-minilla
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEY_MINILLA }}
          export_default_credentials: true
      - run: bash gcloud_run_deploy.blog1-server-go.${{env.GCP_PROJECT_ID}}.sh