name: deploy-suzuito-minilla

on:
  push:
    tags:
      - "qa"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT_ID: suzuito-minilla
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{env.GCP_PROJECT_ID}}
          service_account_key: ${{ secrets.GCP_SA_KEY_MINILLA }}
          export_default_credentials: true
      - run: gcloud builds submit --tag=gcr.io/${{env.GCP_PROJECT_ID}}/blog1-server-go
      - run: gcloud run deploy blog1-server-go --image=gcr.io/${{env.GCP_PROJECT_ID}}/blog1-server-go:latest --platform=managed --region=asia-northeast1 --allow-unauthenticated --memory=512Mi --cpu=1000m --max-instances=1 \
             --set-env-vars="ENV=dev"