jobs:
  test1:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17.x' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: make test
      - uses: codecov/codecov-action@v2
        with:
          verbose: true
