on:
  pull_request:
jobs:
  test1:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16.x' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: make test
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test2"
  test3:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - run: echo "test3"